# ===================================================
# DELIVERY SERVICE CONFIGURATION
# ===================================================
server.port=8083
spring.application.name=delivery-service

# ---------------------------------------------------
# ActiveMQ
# ---------------------------------------------------
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

app.queue.delivery=delivery.queue

# Simulated delivery timings (milliseconds)
app.delivery.dispatch-time-ms=4000
app.delivery.transit-time-ms=6000

# ---------------------------------------------------
# Order Service integration
# ---------------------------------------------------
order.service.base-url=http://localhost:8081

logging.level.com.foodorder=INFO
